### ISSUE TITLE
Peer-to-peer Code Review Morning Session

### ISSUE THREAD

**Issue by rubydevi** [migo1/portfolio#5]
- I suggest avoiding long class names so that mistakes and errors are minimized in CSS stylesheet. eg; In case of `btn-primary-outline` you can add a simple short name of your choice.
- The file paths of images are incorrect
- Please use semantic tags like `section` etc.
- `hr ` tag in **About** section is not closed properly.

**Comment by migo1** [comment]
thanks for raising the issue, I corrected the `hr` tag and shortened the long class name, I just checked on the file path and semantics, and they are ok
